#
# Copyright (c) 2019, 2020 Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Docker for creating container to update version of fdk node package

FROM ocr-docker-remote.artifactory.oci.oraclecorp.com/os/oraclelinux:8-slim

RUN microdnf module enable nodejs:20 && \
    microdnf install nodejs npm && \
    microdnf module reset nodejs:20 && \
    microdnf clean all

RUN npm install -g tar@latest

CMD ["node"]

