#
# Copyright (c) 2019, 2020 Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Docker for creating container to run unit tests
FROM  ocr-docker-remote.artifactory.oci.oraclecorp.com/os/oraclelinux:8-slim
RUN microdnf install yum && \
    yum install -y git && \
    yum install -y make && \
    curl -L https://git.io/n-install --output n-install && \
    chmod +x n-install && \
    yes y | ./n-install && \
    $HOME/n/bin/n 9 && \
    yum clean all && \
    microdnf clean all

RUN mkdir  /build
COPY . /build
WORKDIR /build
RUN echo $'registry=https://artifactory.oci.oraclecorp.com/api/npm/global-release-npm \n@types:registry=https://artifactory.oci.oraclecorp.com/api/npm/global-release-npm \nstrict-ssl=false'> ~/.npmrc