ARG CODE_ONLY_FN_RUNTIME_IMAGE_VERSION

FROM odo-docker-signed-local.artifactory-builds.oci.oraclecorp.com/fdk-node:${CODE_ONLY_FN_RUNTIME_IMAGE_VERSION}

WORKDIR /function
RUN echo $'registry=https://artifactory.oci.oraclecorp.com/api/npm/global-release-npm \n@types:registry=https://artifactory.oci.oraclecorp.com/api/npm/global-release-npm \nstrict-ssl=false'> ~/.npmrc

COPY package.json /function/package.json
RUN npm install

COPY func.js /function/func.js

RUN chmod -R o+r /function
ENTRYPOINT ["node", "func.js"]