name: Publish @fnproject/fdk npm Package
on:
  push:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - run: npm --version
      - run: node -v
      - run: npm ci
      - run: npm test
      - run: npm publish --dry-run=true
      - name: Publish Package to npm registry if branch is master
        if: ${{ github.ref == 'refs/heads/master'}}
        run: npm publish --access public
